name: Release

on:
  push:
    branches:
      - master

env:
  CI: true
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  INITIAL_VERSION: 1.0.0
  DEFAULT_BUMP: patch

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Create Artifact for Repository
        run: zip -qq -x *.git* -r release.zip .

      - name: Bump version and push tag
        id: bump_version
        uses: anothrNick/github-tag-action@1.33.0

      - name: Create Github Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ steps.bump_version.outputs.tag }}
          release_name: ${{ steps.bump_version.outputs.tag }}
          draft: false
          prerelease: false

      - name: Upload Github Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./release.zip
          asset_name: release.zip
          asset_content_type: application/zip
